<?php
  include('connectDB.php');
  include('getBrands.php');
  include('getCats.php');
  include('getOS.php');
  include('selectCats.php');
  include('selectBrands.php');
  include('getRandomProducts.php');
  include('category.php');
  include('brand.php');
  include('getAllProducts.php');